use_frameworks!

platform :ios, '10.0'

target 'FlutterFrameworks_Example' do
  pod 'FlutterFrameworks', :path => '../'

  target 'FlutterFrameworks_Tests' do
    inherit! :search_paths

    
  end
end
